export type Step = 'before' | 'dday' | 'after';
export type EmailLanguage = 'FR' | 'EN';

export type LancementKit = {
  id: string;
  title: string;
  step: Step;
  language: EmailLanguage;
};

export type AnimationItem = {
  id: string;
  title: string;
  month: string;
  type: string;
  status: string;
  landing?: string;
  languages: string[];
  imagesFr: string[];
  imagesEn: string[];
  pdfFr: string[];
  pdfEn: string[];
};

export type EmailTopicKit = {
  id: string;
  title: string;
  topic: string;
  language: EmailLanguage;
};

export const lancementKits: LancementKit[] = [
  { id: "lan-0", title: "Email pré-onboarding - collaborateurs", step: "before", language: "FR" },
  { id: "lan-1", title: "Email pré-onboarding - managers", step: "before", language: "FR" },
  { id: "lan-2", title: "Email pré-onboarding - ambassadeurs", step: "before", language: "FR" },
  { id: "lan-3", title: "Email pré-onboarding - équipes RH", step: "before", language: "FR" },
  { id: "lan-4", title: "Email pré-onboarding - Élus", step: "before", language: "FR" },
  { id: "lan-5", title: "Email pré-onboarding - CODIR", step: "before", language: "FR" },
  { id: "lan-6", title: "Email pré-onboarding - Soignants", step: "before", language: "FR" },
  { id: "lan-7", title: "Relance email pré-onboarding", step: "dday", language: "FR" },
  { id: "lan-8", title: "Invitation calendrier onboarding", step: "dday", language: "FR" },
  { id: "lan-9", title: "Email post-onboarding", step: "after", language: "FR" },
  { id: "lan-10", title: "Prérequis IT", step: "before", language: "FR" },
  { id: "lan-11", title: "Email onboarding managers - Zoom Coaching", step: "before", language: "FR" },
  { id: "lan-12", title: "Pre-onboarding email - employees", step: "before", language: "EN" },
  { id: "lan-13", title: "Pre-onboarding email - managers", step: "before", language: "EN" },
  { id: "lan-14", title: "Pre-onboarding follow-up email", step: "dday", language: "EN" },
  { id: "lan-15", title: "Onboarding calendar invitation", step: "dday", language: "EN" },
  { id: "lan-16", title: "Post-onboarding email", step: "after", language: "EN" },
  { id: "lan-17", title: "New re-onboarding email - employees", step: "before", language: "EN" },
  { id: "lan-18", title: "IT Prerequisites", step: "before", language: "EN" },
  { id: "lan-19", title: "Email reonboarding - collaborateurs - Premiers Pas Santé Mentale + Joy", step: "after", language: "FR" },
  { id: "lan-20", title: "Email reonboarding - collaborateurs - Focus Emotions", step: "after", language: "FR" },
];

export const animationItems: AnimationItem[] = [
  {
    id: "ani-0",
    title: "Breaking out of loneliness / Sortir de la solitude",
    month: "January",
    type: "Playlist",
    status: "Archive",
    languages: ["FR", "EN"],
    imagesFr: ["Sortir de la solitude - desktop png.png", "Sortir de la solitude square.png"],
    imagesEn: ["Breaking free from loneliness Desktop.png", "Breaking free from loneliness Square.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-1",
    title: "🇫🇷 Booster sa confiance en soi pour 2026, loin des mythes et des clichés",
    month: "January",
    type: "Let's talk",
    status: "Archive",
    languages: ["FR"],
    imagesFr: ["[Let's talk] Booster sa confiance en soi — Frédéric Fanget - Janvier 2026 - Desktop A.png", "[Let's talk] Booster sa confiance en soi — Frédéric Fanget - Janvier 2026 - Square A.png"],
    imagesEn: [],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-2",
    title: "🇫🇷🇬🇧 Christmas Mind / Esprit de noël",
    month: "December",
    type: "Playlist",
    status: "Archive",
    languages: ["FR", "EN"],
    imagesFr: [],
    imagesEn: [],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-3",
    title: "🇫🇷 En 2026 : tenir ses bonnes résolutions sans procrastination",
    month: "December",
    type: "Let's talk",
    status: "Archive",
    languages: ["FR", "EN"],
    imagesFr: [],
    imagesEn: [],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-4",
    title: "🇫🇷 Mental health: when social media becomes our therapist / Santé mentale : quand les réseaux sociaux deviennent nos psys",
    month: "November",
    type: "Playlist",
    status: "Archive",
    languages: ["FR"],
    imagesFr: ["Let's talk novembre 2025 desktop A.png", "Let's talk Meditation novembre 2025 catherine la psy.png"],
    imagesEn: [],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-5",
    title: "🇫🇷🇬🇧 Movember",
    month: "November",
    type: "Playlist",
    status: "Archive",
    languages: ["FR", "EN"],
    imagesFr: ["Même pas mâle desktop.png", "Même pas mâle square (2).png"],
    imagesEn: ["Movember desktop banner.png", "Même pas mâle square (3).png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-6",
    title: "🇫🇷🇬🇧 Smoke-Free Month / Mois sans tabac",
    month: "November",
    type: "Playlist",
    status: "Archive",
    languages: ["FR", "EN"],
    imagesFr: ["Mois sans tabac slack : teams.png", "Mois sans tabac desktop.png"],
    imagesEn: ["Quit smoking square.png", "Quit smoking desktop.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-7",
    title: "🇫🇷🇬🇧 Awareness of psychological disabilities / Sensibilisation au handicap psychique",
    month: "November",
    type: "Playlist",
    status: "Archive",
    languages: ["FR", "EN"],
    imagesFr: ["Se sensibiliser au handicap psychique SQUARE FR A.png", "Se sensibiliser au handicap psychique FR A.png", "Se sensibiliser au handicap psychique mobile FR.png", "Se sensibiliser au handicap psychique idee recue 1.png", "Se sensibiliser au handicap psychique idee recue 2.png", "Se sensibiliser au handicap psychique idee recue 3.png"],
    imagesEn: ["Raising awareness about mental disabilities A.png", "Se sensibiliser au handicap psychique SQUARE EN.png", "Se sensibiliser au handicap psychique SQUARE EN A.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-8",
    title: "🇫🇷 Meditation and mental health / Méditation et santé mentale",
    month: "September",
    type: "Let's talk",
    status: "Archive",
    languages: ["FR"],
    imagesFr: ["Let's talk Francois Bourgognon — Desktop.png", "Let's talk Francois Bourgognon — Mobile.png"],
    imagesEn: [],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-9",
    title: "🇫🇷 Meditation challenge / Challenge méditation",
    month: "September",
    type: "Playlist",
    status: "Archive",
    languages: ["FR"],
    imagesFr: ["Challenge Meditation — Desktop FR.png", "Challenge Meditation — Mobile FR.png", "Challenge Meditation — Square FR.png"],
    imagesEn: [],
    pdfFr: ["Poster FR - Meditation FR.pdf"],
    pdfEn: [],
  },
  {
    id: "ani-10",
    title: "🇬🇧 How to Surround Yourself with Uplifting People?",
    month: "October",
    type: "Playlist",
    status: "Archive",
    languages: ["EN"],
    imagesFr: [],
    imagesEn: ["[Let's talk] How to Surround Yourself with Uplifting People — Anaïs Roux — Desktop.png", "[Let's talk] How to Surround Yourself with Uplifting People — Anaïs Roux — Mobile.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-11",
    title: "🇫🇷 Comment (re)créer du collectif à l’heure du phygital ?",
    month: "October",
    type: "Playlist",
    status: "Archive",
    languages: ["FR"],
    imagesFr: ["[Let's talk] Isabelle Barth recréer du collectif à l'heure du phygital desktop.png", "[Let's talk] Isabelle Barth recréer du collectif à l'heure du phygital mobile.png"],
    imagesEn: [],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-12",
    title: "🇫🇷 Comment bien s’entourer dans la vie ?",
    month: "October",
    type: "Playlist",
    status: "Archive",
    languages: ["FR"],
    imagesFr: ["[Let's talk] Comment bien s'entourer dans la vie — Anaïs Roux — Mobile.png", "[Let's talk] Comment bien s'entourer dans la vie — Anaïs Roux — Desktop.png"],
    imagesEn: [],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-13",
    title: "🇫🇷🇬🇧 Octobre Rose",
    month: "October",
    type: "Playlist",
    status: "Archive",
    languages: ["FR"],
    imagesFr: ["Octobre rose.png", "Octobre Rose desktop.png", "Octobre rose carre.png", "Octobre rose mobile.png"],
    imagesEn: [],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-14",
    title: "Être aidant auprès d’un proche malade / Caring for a sick relative",
    month: "February",
    type: "Playlist",
    status: "Archive",
    languages: ["FR", "EN"],
    imagesFr: ["Etre aidant aupres d'un proche malade - Square FR.png", "Etre aidant aupres d'un proche malade - Desktop FR.png"],
    imagesEn: ["Caring for a sick relative - Square EN.png", "Caring for a sick relative - Desktop EN.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-15",
    title: "The Many Faces of Love / L’Amour dans tous ses états",
    month: "February",
    type: "Playlist",
    status: "Archive",
    languages: ["FR"],
    imagesFr: ["February 26 - L'amour dans tous ses états - Square FR.png", "February 26 - L'amour dans tous ses états - Desktop FR 2.png"],
    imagesEn: ["February 26 - L'amour dans tous ses états - Square EN.png", "February 26 - L'amour dans tous ses états - Desktop EN.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-16",
    title: "🇫🇷 Cerveau, amour et rupture (avec Aurore Malet-Karas)",
    month: "February",
    type: "Let's talk",
    status: "Archive",
    languages: ["FR", "EN"],
    imagesFr: ["[Let's talk] Cerveau, amour et rupture - Desktop - FR.png", "[Let's talk] Cerveau, amour et rupture - Square - FR.png"],
    imagesEn: ["[Let's talk] Cerveau, amour et rupture - Desktop - EN.png", "[Let's talk] Cerveau, amour et rupture - Square - EN.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-17",
    title: "🇫🇷 Protéger sa santé mentale face aux rumeurs et aux ragots / Protect Your Mental Health from Office Gossip",
    month: "March",
    type: "Let's talk",
    status: "Archive",
    languages: ["FR", "EN"],
    imagesFr: ["[Let's talk] Protéger sa santé mentale des rumeurs et ragots  - Square - FR.png", "[Let's talk] Protéger sa santé mentale des rumeurs et ragots  - Desktop - FR.png"],
    imagesEn: ["[Let's talk] Protect Your Mental Health from Office Gossip - Square - EN.png", "[Let's talk] Protéger sa santé mentale des rumeurs et ragots  - Desktop - FR.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-18",
    title: "Mental health and women’s hormonal health / Santé mentale et vie hormonale des femmes",
    month: "March",
    type: "Playlist",
    status: "Archive",
    languages: ["FR", "EN"],
    imagesFr: ["[March 2026] Vie Hormonale et Santé Mentale Desktop FR 2.png", "[March 2026] Vie Hormonale et Santé Mentale Square FR.png"],
    imagesEn: ["[March 2026] Hormonal Health Desktop.png", "[March 2026] Hormonal Health Square.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-19",
    title: "🇫🇷🇬🇧 Bien nourrir son cerveau / Fuel your brain properly",
    month: "March",
    type: "Playlist",
    status: "Archive",
    languages: ["FR", "EN"],
    imagesFr: ["[March 2026] Alimentation x Santé mentale desktop FR 2.png", "[March 2026] Alimentation x Santé mentale Square FR.png"],
    imagesEn: ["[March 2026] Food x Mental Health desktop EN 2.png", "[March 2026] Food x Mental Health Square EN.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-20",
    title: "🇫🇷 Sommeil : 5 idées reçues qui vous empêchent de bien dormir / Sleep: 5 common misconceptions that stop you from sleeping well",
    month: "April",
    type: "Let's talk",
    status: "Archive",
    landing: "https://app.livestorm.co/teale-1/lets-talk-sommeil-idees-recues-philippe-beaulieu?utm_campaign=hr",
    languages: ["FR"],
    imagesFr: ["[Let's talk] April 2026 - Sleep - Beaulieu - Square FR.png", "[Let's talk] April 2026 - Sleep - Beaulieu - Desktop FR.png"],
    imagesEn: ["[Let's talk] April 2026 - Sleep - Beaulieu - Square EN.png", "[Let's talk] April 2026 - Sleep - Beaulieu - Desktop EN.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-21",
    title: "🇫🇷🇬🇧 Améliorer son sommeil en quelques semaines / Getting Quality Sleep Back",
    month: "April",
    type: "Playlist",
    status: "Current / En ce moment",
    landing: "https://my.teale.app/series/699327cedfaf06226570eaf0?utm_source=email&utm_campaign=sommeil_2026_hr&utm_medium=email-marketing",
    languages: ["FR", "EN"],
    imagesFr: ["[April 2026] Ameliorez votre votre sommeil Banner.png", "[April 2026] Ameliorez votre votre sommeil Square FR.png"],
    imagesEn: ["[April 2026] Getting Quality Sleep Back Banner.png", "[April 2026] Getting Quality Sleep Back Square.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-22",
    title: "🇫🇷 Gérer son stress financier / Manage your financial stress",
    month: "May",
    type: "Playlist",
    status: "Upcoming / À venir",
    landing: "https://my.teale.app/series/65f473d0da5bb8bc352e48ce?utm_source=email&utm_campaign=stress_financier_2026_hr&utm_medium=email-marketing",
    languages: ["FR"],
    imagesFr: ["[Let's talk] Mental skills for high-pressure work - Square FR.png", "[Playlist][Desktop FR] Gerer son stress financier.png"],
    imagesEn: ["[Let's talk] Mental skills for high-pressure work - Square EN.png", "[Playlist][Desktop EN] Gerer son stress financier.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-23",
    title: "🇫🇷🇬🇧 Le parcours PMA : un marathon émotionnel / The fertility journey: an emotional journey",
    month: "May",
    type: "Playlist",
    status: "Upcoming / À venir",
    languages: ["FR", "EN"],
    imagesFr: ["[Playlist][Square FR] Parcours PMA.png", "[Playlist][Desktop FR] Parcours PMA 2.png"],
    imagesEn: ["[Playlist][Square EN] Fertility Journey.png", "[Playlist][Desktop EN] Fertility Journey.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-24",
    title: "🇬🇧 Mental Skills for High-Pressure work",
    month: "May",
    type: "Let's talk",
    status: "Current / En ce moment",
    landing: "https://app.livestorm.co/teale-1/mental-skills-for-high-pressure-work-emily-rae?utm_campaign=hr",
    languages: ["EN"],
    imagesFr: ["[Let's talk] Mental skills for high-pressure work - Square FR.png", "[Let's talk] Mental skills for high-pressure work - Desktop FR.png"],
    imagesEn: ["[Let's talk] Mental skills for high-pressure work - Square EN.png", "[Let's talk] Mental skills for high-pressure work - Desktop EN.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-25",
    title: "🌿 Semaine de la QVCT 2026",
    month: "June",
    type: "Playlist",
    status: "Upcoming / À venir",
    landing: "https://slides.teale.io/QVCT2026",
    languages: ["FR"],
    imagesFr: [],
    imagesEn: [],
    pdfFr: ["QVCT Week Slide (1).pdf"],
    pdfEn: ["QVCT Week Slide (1).pdf"],
  },
  {
    id: "ani-26",
    title: "🌿 QVCT week 2026",
    month: "June",
    type: "Playlist",
    status: "Upcoming / À venir",
    landing: "https://slides.teale.io/QVCT2026EN",
    languages: ["EN"],
    imagesFr: [],
    imagesEn: [],
    pdfFr: ["QVCT Week Slide (1).pdf"],
    pdfEn: ["QVCT Week Slide (1).pdf"],
  },
  {
    id: "ani-27",
    title: "🇫🇷🇬🇧 Se protéger du burnout / Protect Yourself",
    month: "June",
    type: "Playlist",
    status: "Upcoming / À venir",
    landing: "https://my.teale.app/series/606f2812ffe6bb0013fdbcfc?utm_source=email&utm_campaign=burnout_2026_hr&utm_medium=email-marketing",
    languages: ["FR", "EN"],
    imagesFr: ["[Playlist][Square FR] Proteger_Burnout.png", "[Playlist][Desktop FR] Proteger_Burnout.png"],
    imagesEn: ["[Playlist][Square EN] Protect_mental_health_work.png", "[Playlist][Desktop EN] [Playlist][Square EN] Protect_mental_health_work.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-28",
    title: "🇫🇷 Burnout : parler du travail peut protéger",
    month: "June",
    type: "Let's talk",
    status: "Upcoming / À venir",
    languages: ["FR", "EN"],
    imagesFr: ["[Let's talk] June 2026 - Burnout - Adrien Bournas - Square FR.png", "[Let's talk] June 2026 - Burnout -Adrien  Bournas - Desktop EN.png"],
    imagesEn: ["[Let's talk] June 2026 - Adrien Burnout - Bournas - Square EN.png", "[Let's talk] June 2026 - Burnout -Adrien  Bournas - Desktop EN.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-29",
    title: "🇬🇧 Goodbye Burnout",
    month: "June",
    type: "Let's talk",
    status: "Upcoming / À venir",
    landing: "https://app.livestorm.co/teale-1/goodbye-burnout?utm_campaign=hr",
    languages: ["EN"],
    imagesFr: [],
    imagesEn: ["[Let's talk] June 2026 - Burnout - Wallace-Hadrill - Square EN.png", "[Let's talk] June 2026 - Burnout - Wallace-Hadrill - Desktop EN.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-30",
    title: "Créer sa routine de santé mentale",
    month: "October",
    type: "Playlist",
    status: "Upcoming / À venir",
    landing: "https://my.teale.app/series/676979af923dfbbaf491e6c8?utm_source=email&utm_campaign=routine_2026&utm_medium=email-marketing",
    languages: ["FR", "EN"],
    imagesFr: ["[Playlist][Desktop FR] Routine santé mentale.png", "[Playlist][Square FR] Routine santé mentale.png"],
    imagesEn: ["[Playlist][Desktop EN] Mental Health Routine.png", "[Playlist][Square EN] Mental Health Routine.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-31",
    title: "Master your Emotions",
    month: "October",
    type: "Playlist",
    status: "Upcoming / À venir",
    landing: "https://my.teale.app/series/66fbe14a89b359c118c75342?utm_source=email&utm_campaign=emotions_comics_2026&utm_medium=email-marketing",
    languages: ["EN"],
    imagesFr: [],
    imagesEn: ["[Playlist][Desktop EN] Master your emotions.png", "[Playlist][Square EN] Master your emotions.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-32",
    title: "🇫🇷 Apaiser ma charge mentale",
    month: "September",
    type: "Playlist",
    status: "Upcoming / À venir",
    landing: "https://my.teale.app/series/6284982862af8e2b345e65af?utm_source=email&utm_medium=email-marketing&utm_campaign=Apaiser-ma-charge-mentale2026",
    languages: ["FR"],
    imagesFr: ["[Playlist][Square FR] Apaiser ma charge mentale.png", "[Playlist][Desktop FR] Apaiser ma charge mentale.png"],
    imagesEn: ["[Playlist][Square FR] Apaiser ma charge mentale.png", "[Playlist][Desktop EN] Apaiser ma charge mentale.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-33",
    title: "🇬🇧 Key steps to keep yourself well",
    month: "October",
    type: "Let's talk",
    status: "Upcoming / À venir",
    languages: ["EN"],
    imagesFr: [],
    imagesEn: ["[Let's talk] October 2026 - Key Steps - Wallace-Hadrill - Square EN.png", "[Let's talk] October 2026 - Key Steps - Wallace-Hadrill - Desktop EN.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-34",
    title: "🇬🇧 Happiness: Developing Positive Emotion",
    month: "September",
    type: "Playlist",
    status: "Upcoming / À venir",
    landing: "https://my.teale.app/series/65f41412da5bb8bc352e224b?utm_source=&utm_medium=&utm_campaign=Happiness---Developing-positive-emotions2026",
    languages: ["EN"],
    imagesFr: [],
    imagesEn: ["[Playlist][Desktop EN] Happiness.png", "[Playlist][Square EN] Happiness.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-35",
    title: "🇫🇷 [Manager] Gérer la charge de travail en se préservant",
    month: "May",
    type: "Playlist",
    status: "Upcoming / À venir",
    landing: "https://my.teale.app/series/69b819e3f08abdd379266fe0?utm_source=&utm_medium=&utm_campaign=managers-gerer-la-charge-de-travail-en-se-preservant-2026",
    languages: ["FR"],
    imagesFr: ["[Playlist][Square FR] Gérer la charge de travail en se préservant.png", "[Playlist][Desktop FR] Gérer la charge de travail en se préservant.png"],
    imagesEn: ["[Playlist][Square EN] Managing your workload while staying balancedt.png", "[Playlist][Desktop EN] Managing your workload while staying balanced.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-36",
    title: "🇫🇷🇬🇧 [Manager] Piloter le changement tout en s’économisant",
    month: "May",
    type: "Playlist",
    status: "Upcoming / À venir",
    landing: "https://my.teale.app/series/69b81321c0f99b0f654d6460",
    languages: ["FR"],
    imagesFr: ["[Playlist][Square FR] Piloter le changement tout en s’économisant.png", "[Playlist][Desktop FR] Piloter le changement tout en s’économisant.png"],
    imagesEn: ["[Playlist][Square EN] Pilot change, protect your energy.png", "[Playlist][Desktop EN] Pilot change, protect your energy.png"],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-37",
    title: "🇫🇷 Premiers gestes en santé mentale",
    month: "October",
    type: "Let's talk",
    status: "Upcoming / À venir",
    languages: [],
    imagesFr: [],
    imagesEn: [],
    pdfFr: [],
    pdfEn: [],
  },
  {
    id: "ani-38",
    title: "🇫🇷 L’IA et vous : adopter les bons réflexes",
    month: "May",
    type: "Let's talk",
    status: "Current / En ce moment",
    languages: ["FR"],
    imagesFr: ["[Let's talk] [May 2026] L'IA et vous - Desktop FR 2.png", "[Let's talk] [May 2026] L'IA et vous - Square FR.png"],
    imagesEn: [],
    pdfFr: [],
    pdfEn: [],
  },
];

export const emailTopicKits: EmailTopicKit[] = [
  { id: "emt-0", title: "Ressources et outils pour s’adapter au changement", topic: "ABILITY TO COPE", language: "FR" },
  { id: "emt-1", title: "Créer sa routine pour optimiser son énergie et réduire son stress", topic: "WORK-LIFE BALANCE", language: "FR" },
  { id: "emt-2", title: "Construire une relation de confiance avec vos collègues", topic: "COHESION", language: "FR" },
  { id: "emt-3", title: "Créer un climat de confiance dans votre équipe (managers)", topic: "COHESION", language: "FR" },
  { id: "emt-4", title: "Les clés pour gérer son stress", topic: "STRESS MANAGEMENT", language: "FR" },
  { id: "emt-5", title: "Comprendre ses sources de stress", topic: "STRESS MANAGEMENT", language: "FR" },
  { id: "emt-6", title: "Se protéger et prendre soin de soi (managers)", topic: "STRESS MANAGEMENT", language: "FR" },
  { id: "emt-7", title: "Maîtriser l’art du feedback avec ses équipes (managers)", topic: "RECOGNITION", language: "FR" },
  { id: "emt-8", title: "Les clés de la reconnaissance au quotidien", topic: "RECOGNITION", language: "FR" },
  { id: "emt-9", title: "Vivre l’instant présent", topic: "EMOTION REGULATION", language: "FR" },
  { id: "emt-10", title: "Cultiver la gratitude au quotidien", topic: "EMOTION REGULATION", language: "FR" },
  { id: "emt-11", title: "Créer un environnement propice aux émotions positives dans son équipe (managers)", topic: "EMOTION REGULATION", language: "FR" },
  { id: "emt-12", title: "Muscler sa résilience au quotidien", topic: "ABILITY TO COPE", language: "FR" },
  { id: "emt-13", title: "Identifier ses forces et mieux s’en servir", topic: "ABILITY TO COPE", language: "FR" },
  { id: "emt-14", title: "Créer un environnement propice à la transformation positive (managers)", topic: "ABILITY TO COPE", language: "FR" },
  { id: "emt-15", title: "Réorganisation : accompagner vos équipes face au changement", topic: "ABILITY TO COPE", language: "FR" },
  { id: "emt-16", title: "Réagir face aux situations à risque au travail", topic: "VALUE ALIGNMENT", language: "FR" },
  { id: "emt-17", title: "Identifier ses valeurs au travail", topic: "VALUE ALIGNMENT", language: "FR" },
  { id: "emt-18", title: "Fatigue, stress… Les signes qui ne trompent pas (managers)", topic: "PHYSICAL WELL-BEING AND STRESS", language: "FR" },
  { id: "emt-19", title: "Protégez votre bien-être pour prévenir l'épuisement professionnel (managers)", topic: "PHYSICAL WELL-BEING AND STRESS", language: "FR" },
  { id: "emt-20", title: "5 astuces pour gérer son stress au quotidien", topic: "PHYSICAL WELL-BEING AND STRESS", language: "FR" },
  { id: "emt-21", title: "Resources and tools to adapt to change", topic: "ABILITY TO COPE", language: "EN" },
  { id: "emt-22", title: "Promote disconnection for your team (managers)", topic: "WORK-LIFE BALANCE", language: "EN" },
  { id: "emt-23", title: "Find the balance between professional and personal life", topic: "WORK-LIFE BALANCE", language: "EN" },
  { id: "emt-24", title: "Create a routine to optimize energy and reduce stress", topic: "WORK-LIFE BALANCE", language: "EN" },
  { id: "emt-25", title: "Build a relationship of trust with colleagues", topic: "COHESION", language: "EN" },
  { id: "emt-26", title: "Create a trusting environment within your team (managers)", topic: "COHESION", language: "EN" },
  { id: "emt-27", title: "Keys to managing your stress", topic: "STRESS MANAGEMENT", language: "EN" },
  { id: "emt-28", title: "Understand your sources of stress", topic: "STRESS MANAGEMENT", language: "EN" },
  { id: "emt-29", title: "Protect yourself and take care of yourself (managers)", topic: "STRESS MANAGEMENT", language: "EN" },
  { id: "emt-30", title: "Master the art of feedback with your teams (managers)", topic: "RECOGNITION", language: "EN" },
  { id: "emt-31", title: "Celebrate collective and individual successes", topic: "RECOGNITION", language: "EN" },
  { id: "emt-32", title: "Live in the present moment", topic: "EMOTION REGULATION", language: "EN" },
  { id: "emt-33", title: "Cultivate gratitude daily", topic: "EMOTION REGULATION", language: "EN" },
  { id: "emt-34", title: "Create an environment conducive to positive emotions within the team. (managers)", topic: "EMOTION REGULATION", language: "EN" },
  { id: "emt-35", title: "Strengthen your resilience daily", topic: "ABILITY TO COPE", language: "EN" },
  { id: "emt-36", title: "Identify your strengths and use them better", topic: "ABILITY TO COPE", language: "EN" },
  { id: "emt-37", title: "Create an environment conducive to positive transformation (managers)", topic: "ABILITY TO COPE", language: "EN" },
  { id: "emt-38", title: "React to risky situations at work", topic: "VALUE ALIGNMENT", language: "EN" },
  { id: "emt-39", title: "Identify your values at work", topic: "VALUE ALIGNMENT", language: "EN" },
  { id: "emt-40", title: "Manage well-being: support sleep and understand burnout (managers)", topic: "PHYSICAL WELL-BEING AND STRESS", language: "EN" },
  { id: "emt-41", title: "5 tips for managing daily stress", topic: "PHYSICAL WELL-BEING AND STRESS", language: "EN" },
];